[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.install]
cmds = ["./mvnw clean package -DskipTests -B"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -Xmx512m -Xms256m -jar target/ecom-stock-sync-0.0.1-SNAPSHOT.jar --spring.profiles.active=railway --server.port=$PORT"
